package mail

import (
	"context"
	"encoding/json"
	"regexp"
	"slices"
	"strings"

	"github.com/roman-16/proton-cli/internal/proton"
)

// A filter written as conditions and actions rather than as a Sieve script.
//
// Proton keeps a filter as a Tree, which is the script structured, and a Sieve,
// which is its text. Only the Tree is sent: the server writes the Sieve from it,
// so the text nobody wants to write by hand is generated by the side that also
// runs it, rather than assembled here out of quoting rules.
//
// The web client also sends a "Simple" object describing the same filter for its
// own builder. Proton stores neither that nor anything derived from it - a
// filter read back has only Tree and Sieve - so there is one description here
// and no second one to disagree with it.

// FilterFields are the parts of a message a condition can test.
var FilterFields = []string{"attachments", "recipient", "sender", "subject"}

// FilterComparators are the ways a condition can test one.
var FilterComparators = []string{"contains", "ends", "is", "matches", "starts"}

// FilterCondition is one test: "the subject contains invoice", or its negation.
type FilterCondition struct {
	Field      string `json:"field"`
	Comparator string `json:"comparator"`
	Value      string `json:"value,omitempty"`
	Negate     bool   `json:"negate,omitempty"`
}

// FilterRule is a filter as somebody describes it: what to look for, and what to
// do about it.
type FilterRule struct {
	Conditions []FilterCondition `json:"conditions"`
	MatchAny   bool              `json:"match_any,omitempty"`
	MoveTo     string            `json:"move_to,omitempty"`
	Labels     []string          `json:"labels"`
	MarkRead   bool              `json:"mark_read,omitempty"`
	Star       bool              `json:"star,omitempty"`
}

var (
	matchTypes = map[string]string{
		"contains": "Contains",
		"ends":     "Ends",
		"is":       "Is",
		"matches":  "Matches",
		"starts":   "Starts",
	}
	conditionHeaders = map[string][]string{
		"recipient": {"To", "Cc", "Bcc"},
		"sender":    {"From"},
		"subject":   {"Subject"},
	}
)

// FilterCreateRule adds a filter built from conditions and actions.
func (s *Service) FilterCreateRule(ctx context.Context, name string, rule FilterRule) (string, error) {
	var r struct{ Filter struct{ ID string } }
	if err := s.C.Decode(ctx, proton.Request{
		Method: "POST", Path: "/mail/v4/filters",
		Body: map[string]any{"Name": name, "Version": sieveVersion, "Tree": rule.tree()},
	}, &r); err != nil {
		return "", err
	}
	return r.Filter.ID, nil
}

// fileInto is where matching mail goes. Proton takes one list for the folder and
// the labels, the folder first, and tells them apart by which of yours it names.
func (r FilterRule) fileInto() []string {
	out := make([]string, 0, len(r.Labels)+1)
	if r.MoveTo != "" {
		out = append(out, r.MoveTo)
	}
	return append(out, r.Labels...)
}

func (r FilterRule) statement() string {
	if r.MatchAny {
		return "any"
	}
	return "all"
}

// tree is the script Proton turns into Sieve.
//
// The shape is the web client's, node for node: two require lines, the spam
// check that stops the rest from running on spam, a comment naming the operator
// and comparators, then the test and what to do.
func (r FilterRule) tree() []any {
	tests := make([]any, 0, len(r.Conditions))
	comparators := make([]string, 0, len(r.Conditions))
	dollar := false
	for _, c := range r.Conditions {
		test, needsDollar := c.test()
		if needsDollar {
			dollar = true
		}
		if c.Negate {
			test = map[string]any{"Test": test, "Type": "Not"}
		}
		tests = append(tests, test)
		comparators = append(comparators, c.commentWord())
	}

	then := make([]any, 0, 4)
	for _, name := range r.fileInto() {
		value, needsDollar := escapeSieveVariables(name)
		if needsDollar {
			dollar = true
		}
		then = append(then, map[string]any{"Name": value, "Type": "FileInto"})
	}
	if flags := r.flags(); len(flags) > 0 {
		then = append(then,
			map[string]any{"Flags": flags, "Type": "AddFlag"},
			map[string]any{"Type": "Keep"})
	}

	tree := []any{
		requireNode("include", "environment", "variables", "relational", "comparator-i;ascii-numeric", "spamtest"),
		requireNode("fileinto", "imap4flags"),
	}
	tree = append(tree, spamTestNodes()...)
	if dollar {
		tree = append(tree, map[string]any{"Name": "dollar", "Value": "$", "Flags": []string{}, "Type": "Set"})
	}
	return append(tree,
		comparatorComment(r.statement(), comparators),
		map[string]any{
			"If":   map[string]any{"Tests": tests, "Type": operatorNode(r.statement())},
			"Then": then,
			"Type": "If",
		})
}

func (r FilterRule) flags() []string {
	flags := make([]string, 0, 2)
	if r.MarkRead {
		flags = append(flags, `\Seen`)
	}
	if r.Star {
		flags = append(flags, `\Flagged`)
	}
	return flags
}

// test is the node that does the looking. The second result asks for the node
// that makes a literal dollar sign survive Sieve's variable expansion.
func (c FilterCondition) test() (map[string]any, bool) {
	if c.Field == "attachments" {
		return map[string]any{"Headers": []string{"X-Attached"}, "Type": "Exists"}, false
	}
	match, key := matchTypes[c.Comparator], c.Value
	// Sieve has no "begins with" or "ends with": both are a wildcard match, which
	// is why the value is escaped here and nowhere else - a literal * in it would
	// otherwise become a wildcard of the user's own making.
	switch c.Comparator {
	case "starts":
		match, key = "Matches", escapeSieveWildcards(c.Value)+"*"
	case "ends":
		match, key = "Matches", "*"+escapeSieveWildcards(c.Value)
	}
	value, dollar := escapeSieveVariables(key)
	test := map[string]any{
		"Headers": conditionHeaders[c.Field],
		"Keys":    []any{value},
		"Match":   map[string]any{"Type": match},
		"Format":  map[string]any{"Type": "UnicodeCaseMap"},
		"Type":    "Header",
	}
	if c.Field != "subject" {
		test["Type"] = "Address"
		test["AddressPart"] = map[string]any{"Type": "All"}
	}
	return test, dollar
}

// commentWord is how this condition is named in the comment the builder reads
// back. An attachment test has no comparator of its own.
func (c FilterCondition) commentWord() string {
	word := c.Comparator
	if c.Field == "attachments" {
		word = "default"
	}
	if c.Negate {
		return "!" + word
	}
	return word
}

func requireNode(list ...string) map[string]any {
	return map[string]any{"List": list, "Type": "Require"}
}

func operatorNode(statement string) string {
	if statement == "any" {
		return "AnyOf"
	}
	return "AllOf"
}

// spamTestNodes stop the filter running on mail Proton already called spam.
func spamTestNodes() []any {
	return []any{
		map[string]any{"Text": "# Generated: Do not run this script on spam messages", "Type": "Comment"},
		map[string]any{
			"If": map[string]any{
				"Tests": []any{
					map[string]any{
						"Name": "vnd.proton.spam-threshold", "Keys": []string{"*"},
						"Format": nil, "Match": map[string]any{"Type": "Matches"}, "Type": "Environment",
					},
					map[string]any{
						"Value": map[string]any{"Value": "${1}", "Type": "VariableString"},
						"Flags": []string{}, "Format": map[string]any{"Type": "ASCIINumeric"},
						"Match": map[string]any{"Comparator": "ge", "Type": "GreaterEqualsValue"},
						"Type":  "SpamTest",
					},
				},
				"Type": "AllOf",
			},
			"Then": []any{map[string]any{"Type": "Return"}},
			"Type": "If",
		},
	}
}

// comparatorComment is how the builder recognises its own work: reading a filter
// back means matching this comment against the tests below it.
func comparatorComment(statement string, comparators []string) map[string]any {
	lines := []string{"/**"}
	if statement == "any" {
		lines = append(lines, " @type or")
	} else {
		lines = append(lines, " @type and")
	}
	for _, c := range comparators {
		lines = append(lines, " @comparator "+c)
	}
	lines = append(lines, "/")
	return map[string]any{"Text": strings.Join(lines, "\r\n *"), "Type": "Comment"}
}

// escapeSieveWildcards hides * and ? from a wildcard match.
func escapeSieveWildcards(text string) string {
	return strings.ReplaceAll(regexp.MustCompile(`([*?])`).ReplaceAllString(text, `\$1`), `\`, `\\`)
}

var sieveVariable = regexp.MustCompile(`\$(\{[\w._]+\})`)

// escapeSieveVariables keeps a value that looks like a Sieve variable from being
// read as one. Proton spells the escape as a variable holding a dollar sign,
// which is why a value needing it also needs the node that sets it.
func escapeSieveVariables(text string) (any, bool) {
	if !sieveVariable.MatchString(text) {
		return text, false
	}
	// $$ is how a literal dollar survives the replacement: an unescaped ${dollar}
	// reads as a capture group of that name, which there is none of, and the
	// value silently loses the very character being escaped.
	return map[string]any{
		"Value": sieveVariable.ReplaceAllString(text, `$${dollar}${1}`),
		"Type":  "VariableString",
	}, true
}

// ── reading one back ──

// RuleOf reads a filter's tree back as the rule that would produce it.
//
// It reports false for anything the grammar above cannot say - a script somebody
// wrote by hand, or a filter made in a client that offers more than this does.
// That is the whole point of doing it this way round rather than trusting the
// comment: a rule shown in words has to be one that, restated, gives the same
// filter back.
func RuleOf(tree []any) (FilterRule, bool) {
	rule, ok := readRule(tree)
	if !ok {
		return FilterRule{}, false
	}
	// The proof, and the reason this can be trusted: a rule is only what the
	// filter says if rebuilding the filter from it gives back what was there.
	// Anything this grammar cannot say exactly fails here rather than being
	// shown to somebody in words that do not describe their filter.
	if jsonString(rule.tree()) != jsonString(tree) {
		return FilterRule{}, false
	}
	return rule, true
}

func readRule(tree []any) (FilterRule, bool) {
	rule := FilterRule{Labels: []string{}}
	body, ok := lastIf(tree)
	if !ok {
		return rule, false
	}
	test, _ := body["If"].(map[string]any)
	rule.MatchAny = str(test["Type"]) == "AnyOf"
	tests, _ := test["Tests"].([]any)
	// Sieve has no begins-with, so `starts` and a `matches` the user wrote by
	// hand arrive as the same test. The comment is what tells them apart, which
	// is what Proton writes it for.
	named := commentComparators(tree)
	for i, t := range tests {
		cond, ok := conditionOf(t)
		if !ok {
			return FilterRule{}, false
		}
		if i < len(named) {
			word, negated := strings.CutPrefix(named[i], "!")
			if word != "default" && !slices.Contains(FilterComparators, word) {
				return FilterRule{}, false
			}
			if word != "default" {
				cond.Comparator = word
			}
			cond.Negate = negated
			unwrapWildcard(&cond)
		}
		rule.Conditions = append(rule.Conditions, cond)
	}
	then, _ := body["Then"].([]any)
	for _, action := range then {
		a, _ := action.(map[string]any)
		switch str(a["Type"]) {
		case "FileInto":
			name, ok := a["Name"].(string)
			if !ok {
				return FilterRule{}, false
			}
			rule.Labels = append(rule.Labels, name)
		case "AddFlag":
			flags, _ := a["Flags"].([]any)
			for _, f := range flags {
				switch str(f) {
				case `\Seen`:
					rule.MarkRead = true
				case `\Flagged`:
					rule.Star = true
				default:
					return FilterRule{}, false
				}
			}
		case "Keep":
		default:
			return FilterRule{}, false
		}
	}
	if len(rule.Conditions) == 0 {
		return FilterRule{}, false
	}
	return rule, true
}

// commentComparators reads the comment back, one word per condition below it.
func commentComparators(tree []any) []string {
	var out []string
	for i := len(tree) - 1; i >= 0; i-- {
		node, _ := tree[i].(map[string]any)
		text := str(node["Text"])
		if str(node["Type"]) != "Comment" || !strings.HasPrefix(text, "/**") {
			continue
		}
		for _, line := range strings.Split(text, "\r\n") {
			if word, ok := strings.CutPrefix(strings.TrimPrefix(line, " *"), " @comparator "); ok {
				out = append(out, word)
			}
		}
		return out
	}
	return out
}

func jsonString(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	return string(b)
}

// lastIf is the filter's own test, which is the last one: the spam check comes
// first and every generated tree has it.
func lastIf(tree []any) (map[string]any, bool) {
	for i := len(tree) - 1; i >= 0; i-- {
		node, _ := tree[i].(map[string]any)
		if str(node["Type"]) == "If" {
			return node, true
		}
	}
	return nil, false
}

func conditionOf(t any) (FilterCondition, bool) {
	node, _ := t.(map[string]any)
	var cond FilterCondition
	if str(node["Type"]) == "Not" {
		cond.Negate = true
		node, _ = node["Test"].(map[string]any)
	}
	headers := strs(node["Headers"])
	if str(node["Type"]) == "Exists" {
		if len(headers) != 1 || headers[0] != "X-Attached" {
			return cond, false
		}
		cond.Field, cond.Comparator = "attachments", "contains"
		return cond, true
	}
	for field, want := range conditionHeaders {
		if slices.Equal(headers, want) {
			cond.Field = field
		}
	}
	if cond.Field == "" {
		return cond, false
	}
	keys := strs(node["Keys"])
	if len(keys) != 1 {
		return cond, false
	}
	match, _ := node["Match"].(map[string]any)
	cond.Value = keys[0]
	for comparator, name := range matchTypes {
		if name == str(match["Type"]) {
			cond.Comparator = comparator
		}
	}
	return cond, cond.Comparator != ""
}

// unwrapWildcard takes the value back out of the wildcard match that begins-with
// and ends-with are written as. Only the comment knows which of the three a
// match really was, so this runs after it has said.
func unwrapWildcard(cond *FilterCondition) {
	switch cond.Comparator {
	case "starts":
		cond.Value = unescapeSieveWildcards(strings.TrimSuffix(cond.Value, "*"))
	case "ends":
		cond.Value = unescapeSieveWildcards(strings.TrimPrefix(cond.Value, "*"))
	}
}

// unescapeSieveWildcards undoes escapeSieveWildcards.
func unescapeSieveWildcards(text string) string {
	return regexp.MustCompile(`\\\\([*?])`).ReplaceAllString(text, `$1`)
}

func str(v any) string { s, _ := v.(string); return s }

func strs(v any) []string {
	items, _ := v.([]any)
	out := make([]string, 0, len(items))
	for _, i := range items {
		out = append(out, str(i))
	}
	return out
}
