// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: item-v1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WifiSecurity int32

const (
	WifiSecurity_UnspecifiedWifiSecurity WifiSecurity = 0
	WifiSecurity_WPA                     WifiSecurity = 1
	WifiSecurity_WPA2                    WifiSecurity = 2
	WifiSecurity_WPA3                    WifiSecurity = 3
	WifiSecurity_WEP                     WifiSecurity = 4
)

// Enum value maps for WifiSecurity.
var (
	WifiSecurity_name = map[int32]string{
		0: "UnspecifiedWifiSecurity",
		1: "WPA",
		2: "WPA2",
		3: "WPA3",
		4: "WEP",
	}
	WifiSecurity_value = map[string]int32{
		"UnspecifiedWifiSecurity": 0,
		"WPA":                     1,
		"WPA2":                    2,
		"WPA3":                    3,
		"WEP":                     4,
	}
)

func (x WifiSecurity) Enum() *WifiSecurity {
	p := new(WifiSecurity)
	*p = x
	return p
}

func (x WifiSecurity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiSecurity) Descriptor() protoreflect.EnumDescriptor {
	return file_item_v1_proto_enumTypes[0].Descriptor()
}

func (WifiSecurity) Type() protoreflect.EnumType {
	return &file_item_v1_proto_enumTypes[0]
}

func (x WifiSecurity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiSecurity.Descriptor instead.
func (WifiSecurity) EnumDescriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{0}
}

// Credit cards
type CardType int32

const (
	CardType_Unspecified     CardType = 0
	CardType_Other           CardType = 1
	CardType_Visa            CardType = 2
	CardType_Mastercard      CardType = 3
	CardType_AmericanExpress CardType = 4
)

// Enum value maps for CardType.
var (
	CardType_name = map[int32]string{
		0: "Unspecified",
		1: "Other",
		2: "Visa",
		3: "Mastercard",
		4: "AmericanExpress",
	}
	CardType_value = map[string]int32{
		"Unspecified":     0,
		"Other":           1,
		"Visa":            2,
		"Mastercard":      3,
		"AmericanExpress": 4,
	}
)

func (x CardType) Enum() *CardType {
	p := new(CardType)
	*p = x
	return p
}

func (x CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_item_v1_proto_enumTypes[1].Descriptor()
}

func (CardType) Type() protoreflect.EnumType {
	return &file_item_v1_proto_enumTypes[1]
}

func (x CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardType.Descriptor instead.
func (CardType) EnumDescriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{1}
}

type ItemNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemNote) Reset() {
	*x = ItemNote{}
	mi := &file_item_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemNote) ProtoMessage() {}

func (x *ItemNote) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemNote.ProtoReflect.Descriptor instead.
func (*ItemNote) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{0}
}

type PasskeyCreationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OsName        string                 `protobuf:"bytes,1,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsVersion     string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	AppVersion    string                 `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasskeyCreationData) Reset() {
	*x = PasskeyCreationData{}
	mi := &file_item_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasskeyCreationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasskeyCreationData) ProtoMessage() {}

func (x *PasskeyCreationData) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasskeyCreationData.ProtoReflect.Descriptor instead.
func (*PasskeyCreationData) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{1}
}

func (x *PasskeyCreationData) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *PasskeyCreationData) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *PasskeyCreationData) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *PasskeyCreationData) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type Passkey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KeyId           string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Content         []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Domain          string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	RpId            string                 `protobuf:"bytes,4,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	RpName          string                 `protobuf:"bytes,5,opt,name=rp_name,json=rpName,proto3" json:"rp_name,omitempty"`
	UserName        string                 `protobuf:"bytes,6,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserDisplayName string                 `protobuf:"bytes,7,opt,name=user_display_name,json=userDisplayName,proto3" json:"user_display_name,omitempty"`
	UserId          []byte                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreateTime      uint32                 `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Note            string                 `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	CredentialId    []byte                 `protobuf:"bytes,11,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	UserHandle      []byte                 `protobuf:"bytes,12,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	CreationData    *PasskeyCreationData   `protobuf:"bytes,13,opt,name=creation_data,json=creationData,proto3" json:"creation_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Passkey) Reset() {
	*x = Passkey{}
	mi := &file_item_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passkey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passkey) ProtoMessage() {}

func (x *Passkey) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passkey.ProtoReflect.Descriptor instead.
func (*Passkey) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Passkey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Passkey) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Passkey) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Passkey) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

func (x *Passkey) GetRpName() string {
	if x != nil {
		return x.RpName
	}
	return ""
}

func (x *Passkey) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Passkey) GetUserDisplayName() string {
	if x != nil {
		return x.UserDisplayName
	}
	return ""
}

func (x *Passkey) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *Passkey) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Passkey) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Passkey) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *Passkey) GetUserHandle() []byte {
	if x != nil {
		return x.UserHandle
	}
	return nil
}

func (x *Passkey) GetCreationData() *PasskeyCreationData {
	if x != nil {
		return x.CreationData
	}
	return nil
}

type ItemLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemEmail     string                 `protobuf:"bytes,1,opt,name=item_email,json=itemEmail,proto3" json:"item_email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Urls          []string               `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"`
	TotpUri       string                 `protobuf:"bytes,4,opt,name=totp_uri,json=totpUri,proto3" json:"totp_uri,omitempty"`
	Passkeys      []*Passkey             `protobuf:"bytes,5,rep,name=passkeys,proto3" json:"passkeys,omitempty"`
	ItemUsername  string                 `protobuf:"bytes,6,opt,name=item_username,json=itemUsername,proto3" json:"item_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemLogin) Reset() {
	*x = ItemLogin{}
	mi := &file_item_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLogin) ProtoMessage() {}

func (x *ItemLogin) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemLogin.ProtoReflect.Descriptor instead.
func (*ItemLogin) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ItemLogin) GetItemEmail() string {
	if x != nil {
		return x.ItemEmail
	}
	return ""
}

func (x *ItemLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ItemLogin) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ItemLogin) GetTotpUri() string {
	if x != nil {
		return x.TotpUri
	}
	return ""
}

func (x *ItemLogin) GetPasskeys() []*Passkey {
	if x != nil {
		return x.Passkeys
	}
	return nil
}

func (x *ItemLogin) GetItemUsername() string {
	if x != nil {
		return x.ItemUsername
	}
	return ""
}

type ItemAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAlias) Reset() {
	*x = ItemAlias{}
	mi := &file_item_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAlias) ProtoMessage() {}

func (x *ItemAlias) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAlias.ProtoReflect.Descriptor instead.
func (*ItemAlias) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{4}
}

type CustomSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionName   string                 `protobuf:"bytes,1,opt,name=section_name,json=sectionName,proto3" json:"section_name,omitempty"`
	SectionFields []*ExtraField          `protobuf:"bytes,2,rep,name=section_fields,json=sectionFields,proto3" json:"section_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomSection) Reset() {
	*x = CustomSection{}
	mi := &file_item_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSection) ProtoMessage() {}

func (x *CustomSection) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSection.ProtoReflect.Descriptor instead.
func (*CustomSection) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{5}
}

func (x *CustomSection) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *CustomSection) GetSectionFields() []*ExtraField {
	if x != nil {
		return x.SectionFields
	}
	return nil
}

type ItemCustom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*CustomSection       `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCustom) Reset() {
	*x = ItemCustom{}
	mi := &file_item_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCustom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCustom) ProtoMessage() {}

func (x *ItemCustom) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCustom.ProtoReflect.Descriptor instead.
func (*ItemCustom) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{6}
}

func (x *ItemCustom) GetSections() []*CustomSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type ItemSSHKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Sections      []*CustomSection       `protobuf:"bytes,3,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemSSHKey) Reset() {
	*x = ItemSSHKey{}
	mi := &file_item_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSSHKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSSHKey) ProtoMessage() {}

func (x *ItemSSHKey) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSSHKey.ProtoReflect.Descriptor instead.
func (*ItemSSHKey) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{7}
}

func (x *ItemSSHKey) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *ItemSSHKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ItemSSHKey) GetSections() []*CustomSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type ItemWifi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ssid          string                 `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Security      WifiSecurity           `protobuf:"varint,3,opt,name=security,proto3,enum=proton_pass_item_v1.WifiSecurity" json:"security,omitempty"`
	Sections      []*CustomSection       `protobuf:"bytes,4,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemWifi) Reset() {
	*x = ItemWifi{}
	mi := &file_item_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemWifi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemWifi) ProtoMessage() {}

func (x *ItemWifi) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemWifi.ProtoReflect.Descriptor instead.
func (*ItemWifi) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{8}
}

func (x *ItemWifi) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *ItemWifi) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ItemWifi) GetSecurity() WifiSecurity {
	if x != nil {
		return x.Security
	}
	return WifiSecurity_UnspecifiedWifiSecurity
}

func (x *ItemWifi) GetSections() []*CustomSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type ItemCreditCard struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CardholderName     string                 `protobuf:"bytes,1,opt,name=cardholder_name,json=cardholderName,proto3" json:"cardholder_name,omitempty"`
	CardType           CardType               `protobuf:"varint,2,opt,name=card_type,json=cardType,proto3,enum=proton_pass_item_v1.CardType" json:"card_type,omitempty"`
	Number             string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	VerificationNumber string                 `protobuf:"bytes,4,opt,name=verification_number,json=verificationNumber,proto3" json:"verification_number,omitempty"`
	// Expected format: YYYY-MM, always containing two numbers for the month, even if is 01
	ExpirationDate string `protobuf:"bytes,5,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	Pin            string `protobuf:"bytes,6,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ItemCreditCard) Reset() {
	*x = ItemCreditCard{}
	mi := &file_item_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCreditCard) ProtoMessage() {}

func (x *ItemCreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCreditCard.ProtoReflect.Descriptor instead.
func (*ItemCreditCard) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{9}
}

func (x *ItemCreditCard) GetCardholderName() string {
	if x != nil {
		return x.CardholderName
	}
	return ""
}

func (x *ItemCreditCard) GetCardType() CardType {
	if x != nil {
		return x.CardType
	}
	return CardType_Unspecified
}

func (x *ItemCreditCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *ItemCreditCard) GetVerificationNumber() string {
	if x != nil {
		return x.VerificationNumber
	}
	return ""
}

func (x *ItemCreditCard) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

func (x *ItemCreditCard) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type ItemIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Personal details
	// Shown
	FullName    string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Additional
	FirstName            string        `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName           string        `protobuf:"bytes,5,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName             string        `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Birthdate            string        `protobuf:"bytes,7,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Gender               string        `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	ExtraPersonalDetails []*ExtraField `protobuf:"bytes,9,rep,name=extra_personal_details,json=extraPersonalDetails,proto3" json:"extra_personal_details,omitempty"`
	// Address details
	// Shown
	Organization    string `protobuf:"bytes,10,opt,name=organization,proto3" json:"organization,omitempty"`
	StreetAddress   string `protobuf:"bytes,11,opt,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"`
	ZipOrPostalCode string `protobuf:"bytes,12,opt,name=zip_or_postal_code,json=zipOrPostalCode,proto3" json:"zip_or_postal_code,omitempty"`
	City            string `protobuf:"bytes,13,opt,name=city,proto3" json:"city,omitempty"`
	StateOrProvince string `protobuf:"bytes,14,opt,name=state_or_province,json=stateOrProvince,proto3" json:"state_or_province,omitempty"`
	CountryOrRegion string `protobuf:"bytes,15,opt,name=country_or_region,json=countryOrRegion,proto3" json:"country_or_region,omitempty"`
	// Additional
	Floor               string        `protobuf:"bytes,16,opt,name=floor,proto3" json:"floor,omitempty"`
	County              string        `protobuf:"bytes,17,opt,name=county,proto3" json:"county,omitempty"`
	ExtraAddressDetails []*ExtraField `protobuf:"bytes,18,rep,name=extra_address_details,json=extraAddressDetails,proto3" json:"extra_address_details,omitempty"`
	// Contact details
	// Shown
	SocialSecurityNumber string `protobuf:"bytes,19,opt,name=social_security_number,json=socialSecurityNumber,proto3" json:"social_security_number,omitempty"`
	PassportNumber       string `protobuf:"bytes,20,opt,name=passport_number,json=passportNumber,proto3" json:"passport_number,omitempty"`
	LicenseNumber        string `protobuf:"bytes,21,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Website              string `protobuf:"bytes,22,opt,name=website,proto3" json:"website,omitempty"`
	XHandle              string `protobuf:"bytes,23,opt,name=x_handle,json=xHandle,proto3" json:"x_handle,omitempty"`
	SecondPhoneNumber    string `protobuf:"bytes,24,opt,name=second_phone_number,json=secondPhoneNumber,proto3" json:"second_phone_number,omitempty"`
	// Additional
	Linkedin            string        `protobuf:"bytes,25,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	Reddit              string        `protobuf:"bytes,26,opt,name=reddit,proto3" json:"reddit,omitempty"`
	Facebook            string        `protobuf:"bytes,27,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Yahoo               string        `protobuf:"bytes,28,opt,name=yahoo,proto3" json:"yahoo,omitempty"`
	Instagram           string        `protobuf:"bytes,29,opt,name=instagram,proto3" json:"instagram,omitempty"`
	ExtraContactDetails []*ExtraField `protobuf:"bytes,30,rep,name=extra_contact_details,json=extraContactDetails,proto3" json:"extra_contact_details,omitempty"`
	// Work details
	// Shown
	Company  string `protobuf:"bytes,31,opt,name=company,proto3" json:"company,omitempty"`
	JobTitle string `protobuf:"bytes,32,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	// Additional
	PersonalWebsite  string        `protobuf:"bytes,33,opt,name=personal_website,json=personalWebsite,proto3" json:"personal_website,omitempty"`
	WorkPhoneNumber  string        `protobuf:"bytes,34,opt,name=work_phone_number,json=workPhoneNumber,proto3" json:"work_phone_number,omitempty"`
	WorkEmail        string        `protobuf:"bytes,35,opt,name=work_email,json=workEmail,proto3" json:"work_email,omitempty"`
	ExtraWorkDetails []*ExtraField `protobuf:"bytes,36,rep,name=extra_work_details,json=extraWorkDetails,proto3" json:"extra_work_details,omitempty"`
	// Extra sections
	ExtraSections []*CustomSection `protobuf:"bytes,37,rep,name=extra_sections,json=extraSections,proto3" json:"extra_sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemIdentity) Reset() {
	*x = ItemIdentity{}
	mi := &file_item_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemIdentity) ProtoMessage() {}

func (x *ItemIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemIdentity.ProtoReflect.Descriptor instead.
func (*ItemIdentity) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{10}
}

func (x *ItemIdentity) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ItemIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ItemIdentity) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ItemIdentity) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ItemIdentity) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *ItemIdentity) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ItemIdentity) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *ItemIdentity) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ItemIdentity) GetExtraPersonalDetails() []*ExtraField {
	if x != nil {
		return x.ExtraPersonalDetails
	}
	return nil
}

func (x *ItemIdentity) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *ItemIdentity) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *ItemIdentity) GetZipOrPostalCode() string {
	if x != nil {
		return x.ZipOrPostalCode
	}
	return ""
}

func (x *ItemIdentity) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ItemIdentity) GetStateOrProvince() string {
	if x != nil {
		return x.StateOrProvince
	}
	return ""
}

func (x *ItemIdentity) GetCountryOrRegion() string {
	if x != nil {
		return x.CountryOrRegion
	}
	return ""
}

func (x *ItemIdentity) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *ItemIdentity) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

func (x *ItemIdentity) GetExtraAddressDetails() []*ExtraField {
	if x != nil {
		return x.ExtraAddressDetails
	}
	return nil
}

func (x *ItemIdentity) GetSocialSecurityNumber() string {
	if x != nil {
		return x.SocialSecurityNumber
	}
	return ""
}

func (x *ItemIdentity) GetPassportNumber() string {
	if x != nil {
		return x.PassportNumber
	}
	return ""
}

func (x *ItemIdentity) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *ItemIdentity) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *ItemIdentity) GetXHandle() string {
	if x != nil {
		return x.XHandle
	}
	return ""
}

func (x *ItemIdentity) GetSecondPhoneNumber() string {
	if x != nil {
		return x.SecondPhoneNumber
	}
	return ""
}

func (x *ItemIdentity) GetLinkedin() string {
	if x != nil {
		return x.Linkedin
	}
	return ""
}

func (x *ItemIdentity) GetReddit() string {
	if x != nil {
		return x.Reddit
	}
	return ""
}

func (x *ItemIdentity) GetFacebook() string {
	if x != nil {
		return x.Facebook
	}
	return ""
}

func (x *ItemIdentity) GetYahoo() string {
	if x != nil {
		return x.Yahoo
	}
	return ""
}

func (x *ItemIdentity) GetInstagram() string {
	if x != nil {
		return x.Instagram
	}
	return ""
}

func (x *ItemIdentity) GetExtraContactDetails() []*ExtraField {
	if x != nil {
		return x.ExtraContactDetails
	}
	return nil
}

func (x *ItemIdentity) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *ItemIdentity) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *ItemIdentity) GetPersonalWebsite() string {
	if x != nil {
		return x.PersonalWebsite
	}
	return ""
}

func (x *ItemIdentity) GetWorkPhoneNumber() string {
	if x != nil {
		return x.WorkPhoneNumber
	}
	return ""
}

func (x *ItemIdentity) GetWorkEmail() string {
	if x != nil {
		return x.WorkEmail
	}
	return ""
}

func (x *ItemIdentity) GetExtraWorkDetails() []*ExtraField {
	if x != nil {
		return x.ExtraWorkDetails
	}
	return nil
}

func (x *ItemIdentity) GetExtraSections() []*CustomSection {
	if x != nil {
		return x.ExtraSections
	}
	return nil
}

// Client extras
type AllowedAndroidApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Hashes        []string               `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowedAndroidApp) Reset() {
	*x = AllowedAndroidApp{}
	mi := &file_item_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowedAndroidApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedAndroidApp) ProtoMessage() {}

func (x *AllowedAndroidApp) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedAndroidApp.ProtoReflect.Descriptor instead.
func (*AllowedAndroidApp) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{11}
}

func (x *AllowedAndroidApp) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *AllowedAndroidApp) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *AllowedAndroidApp) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type AndroidSpecific struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllowedApps   []*AllowedAndroidApp   `protobuf:"bytes,1,rep,name=allowed_apps,json=allowedApps,proto3" json:"allowed_apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndroidSpecific) Reset() {
	*x = AndroidSpecific{}
	mi := &file_item_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndroidSpecific) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidSpecific) ProtoMessage() {}

func (x *AndroidSpecific) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidSpecific.ProtoReflect.Descriptor instead.
func (*AndroidSpecific) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{12}
}

func (x *AndroidSpecific) GetAllowedApps() []*AllowedAndroidApp {
	if x != nil {
		return x.AllowedApps
	}
	return nil
}

type PlatformSpecific struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Android       *AndroidSpecific       `protobuf:"bytes,1,opt,name=android,proto3" json:"android,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformSpecific) Reset() {
	*x = PlatformSpecific{}
	mi := &file_item_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformSpecific) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformSpecific) ProtoMessage() {}

func (x *PlatformSpecific) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformSpecific.ProtoReflect.Descriptor instead.
func (*PlatformSpecific) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{13}
}

func (x *PlatformSpecific) GetAndroid() *AndroidSpecific {
	if x != nil {
		return x.Android
	}
	return nil
}

type ExtraTotp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotpUri       string                 `protobuf:"bytes,1,opt,name=totp_uri,json=totpUri,proto3" json:"totp_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraTotp) Reset() {
	*x = ExtraTotp{}
	mi := &file_item_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraTotp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraTotp) ProtoMessage() {}

func (x *ExtraTotp) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraTotp.ProtoReflect.Descriptor instead.
func (*ExtraTotp) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{14}
}

func (x *ExtraTotp) GetTotpUri() string {
	if x != nil {
		return x.TotpUri
	}
	return ""
}

type ExtraTextField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraTextField) Reset() {
	*x = ExtraTextField{}
	mi := &file_item_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraTextField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraTextField) ProtoMessage() {}

func (x *ExtraTextField) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraTextField.ProtoReflect.Descriptor instead.
func (*ExtraTextField) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{15}
}

func (x *ExtraTextField) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ExtraHiddenField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraHiddenField) Reset() {
	*x = ExtraHiddenField{}
	mi := &file_item_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraHiddenField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraHiddenField) ProtoMessage() {}

func (x *ExtraHiddenField) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraHiddenField.ProtoReflect.Descriptor instead.
func (*ExtraHiddenField) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{16}
}

func (x *ExtraHiddenField) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ExtraTimestampField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraTimestampField) Reset() {
	*x = ExtraTimestampField{}
	mi := &file_item_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraTimestampField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraTimestampField) ProtoMessage() {}

func (x *ExtraTimestampField) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraTimestampField.ProtoReflect.Descriptor instead.
func (*ExtraTimestampField) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{17}
}

func (x *ExtraTimestampField) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ExtraField struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FieldName string                 `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*ExtraField_Totp
	//	*ExtraField_Text
	//	*ExtraField_Hidden
	//	*ExtraField_Timestamp
	Content       isExtraField_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraField) Reset() {
	*x = ExtraField{}
	mi := &file_item_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraField) ProtoMessage() {}

func (x *ExtraField) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraField.ProtoReflect.Descriptor instead.
func (*ExtraField) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{18}
}

func (x *ExtraField) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *ExtraField) GetContent() isExtraField_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExtraField) GetTotp() *ExtraTotp {
	if x != nil {
		if x, ok := x.Content.(*ExtraField_Totp); ok {
			return x.Totp
		}
	}
	return nil
}

func (x *ExtraField) GetText() *ExtraTextField {
	if x != nil {
		if x, ok := x.Content.(*ExtraField_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ExtraField) GetHidden() *ExtraHiddenField {
	if x != nil {
		if x, ok := x.Content.(*ExtraField_Hidden); ok {
			return x.Hidden
		}
	}
	return nil
}

func (x *ExtraField) GetTimestamp() *ExtraTimestampField {
	if x != nil {
		if x, ok := x.Content.(*ExtraField_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

type isExtraField_Content interface {
	isExtraField_Content()
}

type ExtraField_Totp struct {
	Totp *ExtraTotp `protobuf:"bytes,2,opt,name=totp,proto3,oneof"`
}

type ExtraField_Text struct {
	Text *ExtraTextField `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type ExtraField_Hidden struct {
	Hidden *ExtraHiddenField `protobuf:"bytes,4,opt,name=hidden,proto3,oneof"`
}

type ExtraField_Timestamp struct {
	Timestamp *ExtraTimestampField `protobuf:"bytes,5,opt,name=timestamp,proto3,oneof"`
}

func (*ExtraField_Totp) isExtraField_Content() {}

func (*ExtraField_Text) isExtraField_Content() {}

func (*ExtraField_Hidden) isExtraField_Content() {}

func (*ExtraField_Timestamp) isExtraField_Content() {}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	ItemUuid      string                 `protobuf:"bytes,3,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_item_v1_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{19}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Metadata) GetItemUuid() string {
	if x != nil {
		return x.ItemUuid
	}
	return ""
}

type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// No case 1 to avoid having a default
	//
	// Types that are valid to be assigned to Content:
	//
	//	*Content_Note
	//	*Content_Login
	//	*Content_Alias
	//	*Content_CreditCard
	//	*Content_Identity
	//	*Content_SshKey
	//	*Content_Wifi
	//	*Content_Custom
	Content       isContent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_item_v1_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{20}
}

func (x *Content) GetContent() isContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Content) GetNote() *ItemNote {
	if x != nil {
		if x, ok := x.Content.(*Content_Note); ok {
			return x.Note
		}
	}
	return nil
}

func (x *Content) GetLogin() *ItemLogin {
	if x != nil {
		if x, ok := x.Content.(*Content_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *Content) GetAlias() *ItemAlias {
	if x != nil {
		if x, ok := x.Content.(*Content_Alias); ok {
			return x.Alias
		}
	}
	return nil
}

func (x *Content) GetCreditCard() *ItemCreditCard {
	if x != nil {
		if x, ok := x.Content.(*Content_CreditCard); ok {
			return x.CreditCard
		}
	}
	return nil
}

func (x *Content) GetIdentity() *ItemIdentity {
	if x != nil {
		if x, ok := x.Content.(*Content_Identity); ok {
			return x.Identity
		}
	}
	return nil
}

func (x *Content) GetSshKey() *ItemSSHKey {
	if x != nil {
		if x, ok := x.Content.(*Content_SshKey); ok {
			return x.SshKey
		}
	}
	return nil
}

func (x *Content) GetWifi() *ItemWifi {
	if x != nil {
		if x, ok := x.Content.(*Content_Wifi); ok {
			return x.Wifi
		}
	}
	return nil
}

func (x *Content) GetCustom() *ItemCustom {
	if x != nil {
		if x, ok := x.Content.(*Content_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

type isContent_Content interface {
	isContent_Content()
}

type Content_Note struct {
	Note *ItemNote `protobuf:"bytes,2,opt,name=note,proto3,oneof"`
}

type Content_Login struct {
	Login *ItemLogin `protobuf:"bytes,3,opt,name=login,proto3,oneof"`
}

type Content_Alias struct {
	Alias *ItemAlias `protobuf:"bytes,4,opt,name=alias,proto3,oneof"`
}

type Content_CreditCard struct {
	CreditCard *ItemCreditCard `protobuf:"bytes,5,opt,name=credit_card,json=creditCard,proto3,oneof"`
}

type Content_Identity struct {
	Identity *ItemIdentity `protobuf:"bytes,6,opt,name=identity,proto3,oneof"`
}

type Content_SshKey struct {
	SshKey *ItemSSHKey `protobuf:"bytes,7,opt,name=ssh_key,json=sshKey,proto3,oneof"`
}

type Content_Wifi struct {
	Wifi *ItemWifi `protobuf:"bytes,8,opt,name=wifi,proto3,oneof"`
}

type Content_Custom struct {
	Custom *ItemCustom `protobuf:"bytes,9,opt,name=custom,proto3,oneof"`
}

func (*Content_Note) isContent_Content() {}

func (*Content_Login) isContent_Content() {}

func (*Content_Alias) isContent_Content() {}

func (*Content_CreditCard) isContent_Content() {}

func (*Content_Identity) isContent_Content() {}

func (*Content_SshKey) isContent_Content() {}

func (*Content_Wifi) isContent_Content() {}

func (*Content_Custom) isContent_Content() {}

type Item struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Metadata         *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content          *Content               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	PlatformSpecific *PlatformSpecific      `protobuf:"bytes,3,opt,name=platform_specific,json=platformSpecific,proto3" json:"platform_specific,omitempty"`
	ExtraFields      []*ExtraField          `protobuf:"bytes,4,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_item_v1_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_item_v1_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_item_v1_proto_rawDescGZIP(), []int{21}
}

func (x *Item) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Item) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Item) GetPlatformSpecific() *PlatformSpecific {
	if x != nil {
		return x.PlatformSpecific
	}
	return nil
}

func (x *Item) GetExtraFields() []*ExtraField {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

var File_item_v1_proto protoreflect.FileDescriptor

const file_item_v1_proto_rawDesc = "" +
	"\n" +
	"\ritem-v1.proto\x12\x13proton_pass_item_v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\n" +
	"\n" +
	"\bItemNote\"\x8f\x01\n" +
	"\x13PasskeyCreationData\x12\x17\n" +
	"\aos_name\x18\x01 \x01(\tR\x06osName\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vapp_version\x18\x04 \x01(\tR\n" +
	"appVersion\"\xac\x03\n" +
	"\aPasskey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x13\n" +
	"\x05rp_id\x18\x04 \x01(\tR\x04rpId\x12\x17\n" +
	"\arp_name\x18\x05 \x01(\tR\x06rpName\x12\x1b\n" +
	"\tuser_name\x18\x06 \x01(\tR\buserName\x12*\n" +
	"\x11user_display_name\x18\a \x01(\tR\x0fuserDisplayName\x12\x17\n" +
	"\auser_id\x18\b \x01(\fR\x06userId\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\rR\n" +
	"createTime\x12\x12\n" +
	"\x04note\x18\n" +
	" \x01(\tR\x04note\x12#\n" +
	"\rcredential_id\x18\v \x01(\fR\fcredentialId\x12\x1f\n" +
	"\vuser_handle\x18\f \x01(\fR\n" +
	"userHandle\x12M\n" +
	"\rcreation_data\x18\r \x01(\v2(.proton_pass_item_v1.PasskeyCreationDataR\fcreationData\"\xd4\x01\n" +
	"\tItemLogin\x12\x1d\n" +
	"\n" +
	"item_email\x18\x01 \x01(\tR\titemEmail\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04urls\x18\x03 \x03(\tR\x04urls\x12\x19\n" +
	"\btotp_uri\x18\x04 \x01(\tR\atotpUri\x128\n" +
	"\bpasskeys\x18\x05 \x03(\v2\x1c.proton_pass_item_v1.PasskeyR\bpasskeys\x12#\n" +
	"\ritem_username\x18\x06 \x01(\tR\fitemUsername\"\v\n" +
	"\tItemAlias\"z\n" +
	"\rCustomSection\x12!\n" +
	"\fsection_name\x18\x01 \x01(\tR\vsectionName\x12F\n" +
	"\x0esection_fields\x18\x02 \x03(\v2\x1f.proton_pass_item_v1.ExtraFieldR\rsectionFields\"L\n" +
	"\n" +
	"ItemCustom\x12>\n" +
	"\bsections\x18\x01 \x03(\v2\".proton_pass_item_v1.CustomSectionR\bsections\"\x8c\x01\n" +
	"\n" +
	"ItemSSHKey\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12>\n" +
	"\bsections\x18\x03 \x03(\v2\".proton_pass_item_v1.CustomSectionR\bsections\"\xb9\x01\n" +
	"\bItemWifi\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\tR\x04ssid\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12=\n" +
	"\bsecurity\x18\x03 \x01(\x0e2!.proton_pass_item_v1.WifiSecurityR\bsecurity\x12>\n" +
	"\bsections\x18\x04 \x03(\v2\".proton_pass_item_v1.CustomSectionR\bsections\"\xf9\x01\n" +
	"\x0eItemCreditCard\x12'\n" +
	"\x0fcardholder_name\x18\x01 \x01(\tR\x0ecardholderName\x12:\n" +
	"\tcard_type\x18\x02 \x01(\x0e2\x1d.proton_pass_item_v1.CardTypeR\bcardType\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12/\n" +
	"\x13verification_number\x18\x04 \x01(\tR\x12verificationNumber\x12'\n" +
	"\x0fexpiration_date\x18\x05 \x01(\tR\x0eexpirationDate\x12\x10\n" +
	"\x03pin\x18\x06 \x01(\tR\x03pin\"\xc0\v\n" +
	"\fItemIdentity\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vmiddle_name\x18\x05 \x01(\tR\n" +
	"middleName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x12\x1c\n" +
	"\tbirthdate\x18\a \x01(\tR\tbirthdate\x12\x16\n" +
	"\x06gender\x18\b \x01(\tR\x06gender\x12U\n" +
	"\x16extra_personal_details\x18\t \x03(\v2\x1f.proton_pass_item_v1.ExtraFieldR\x14extraPersonalDetails\x12\"\n" +
	"\forganization\x18\n" +
	" \x01(\tR\forganization\x12%\n" +
	"\x0estreet_address\x18\v \x01(\tR\rstreetAddress\x12+\n" +
	"\x12zip_or_postal_code\x18\f \x01(\tR\x0fzipOrPostalCode\x12\x12\n" +
	"\x04city\x18\r \x01(\tR\x04city\x12*\n" +
	"\x11state_or_province\x18\x0e \x01(\tR\x0fstateOrProvince\x12*\n" +
	"\x11country_or_region\x18\x0f \x01(\tR\x0fcountryOrRegion\x12\x14\n" +
	"\x05floor\x18\x10 \x01(\tR\x05floor\x12\x16\n" +
	"\x06county\x18\x11 \x01(\tR\x06county\x12S\n" +
	"\x15extra_address_details\x18\x12 \x03(\v2\x1f.proton_pass_item_v1.ExtraFieldR\x13extraAddressDetails\x124\n" +
	"\x16social_security_number\x18\x13 \x01(\tR\x14socialSecurityNumber\x12'\n" +
	"\x0fpassport_number\x18\x14 \x01(\tR\x0epassportNumber\x12%\n" +
	"\x0elicense_number\x18\x15 \x01(\tR\rlicenseNumber\x12\x18\n" +
	"\awebsite\x18\x16 \x01(\tR\awebsite\x12\x19\n" +
	"\bx_handle\x18\x17 \x01(\tR\axHandle\x12.\n" +
	"\x13second_phone_number\x18\x18 \x01(\tR\x11secondPhoneNumber\x12\x1a\n" +
	"\blinkedin\x18\x19 \x01(\tR\blinkedin\x12\x16\n" +
	"\x06reddit\x18\x1a \x01(\tR\x06reddit\x12\x1a\n" +
	"\bfacebook\x18\x1b \x01(\tR\bfacebook\x12\x14\n" +
	"\x05yahoo\x18\x1c \x01(\tR\x05yahoo\x12\x1c\n" +
	"\tinstagram\x18\x1d \x01(\tR\tinstagram\x12S\n" +
	"\x15extra_contact_details\x18\x1e \x03(\v2\x1f.proton_pass_item_v1.ExtraFieldR\x13extraContactDetails\x12\x18\n" +
	"\acompany\x18\x1f \x01(\tR\acompany\x12\x1b\n" +
	"\tjob_title\x18  \x01(\tR\bjobTitle\x12)\n" +
	"\x10personal_website\x18! \x01(\tR\x0fpersonalWebsite\x12*\n" +
	"\x11work_phone_number\x18\" \x01(\tR\x0fworkPhoneNumber\x12\x1d\n" +
	"\n" +
	"work_email\x18# \x01(\tR\tworkEmail\x12M\n" +
	"\x12extra_work_details\x18$ \x03(\v2\x1f.proton_pass_item_v1.ExtraFieldR\x10extraWorkDetails\x12I\n" +
	"\x0eextra_sections\x18% \x03(\v2\".proton_pass_item_v1.CustomSectionR\rextraSections\"i\n" +
	"\x11AllowedAndroidApp\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12\x16\n" +
	"\x06hashes\x18\x02 \x03(\tR\x06hashes\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\"\\\n" +
	"\x0fAndroidSpecific\x12I\n" +
	"\fallowed_apps\x18\x01 \x03(\v2&.proton_pass_item_v1.AllowedAndroidAppR\vallowedApps\"R\n" +
	"\x10PlatformSpecific\x12>\n" +
	"\aandroid\x18\x01 \x01(\v2$.proton_pass_item_v1.AndroidSpecificR\aandroid\"&\n" +
	"\tExtraTotp\x12\x19\n" +
	"\btotp_uri\x18\x01 \x01(\tR\atotpUri\"*\n" +
	"\x0eExtraTextField\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\",\n" +
	"\x10ExtraHiddenField\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"O\n" +
	"\x13ExtraTimestampField\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb2\x02\n" +
	"\n" +
	"ExtraField\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x124\n" +
	"\x04totp\x18\x02 \x01(\v2\x1e.proton_pass_item_v1.ExtraTotpH\x00R\x04totp\x129\n" +
	"\x04text\x18\x03 \x01(\v2#.proton_pass_item_v1.ExtraTextFieldH\x00R\x04text\x12?\n" +
	"\x06hidden\x18\x04 \x01(\v2%.proton_pass_item_v1.ExtraHiddenFieldH\x00R\x06hidden\x12H\n" +
	"\ttimestamp\x18\x05 \x01(\v2(.proton_pass_item_v1.ExtraTimestampFieldH\x00R\ttimestampB\t\n" +
	"\acontent\"O\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\x12\x1b\n" +
	"\titem_uuid\x18\x03 \x01(\tR\bitemUuid\"\xee\x03\n" +
	"\aContent\x123\n" +
	"\x04note\x18\x02 \x01(\v2\x1d.proton_pass_item_v1.ItemNoteH\x00R\x04note\x126\n" +
	"\x05login\x18\x03 \x01(\v2\x1e.proton_pass_item_v1.ItemLoginH\x00R\x05login\x126\n" +
	"\x05alias\x18\x04 \x01(\v2\x1e.proton_pass_item_v1.ItemAliasH\x00R\x05alias\x12F\n" +
	"\vcredit_card\x18\x05 \x01(\v2#.proton_pass_item_v1.ItemCreditCardH\x00R\n" +
	"creditCard\x12?\n" +
	"\bidentity\x18\x06 \x01(\v2!.proton_pass_item_v1.ItemIdentityH\x00R\bidentity\x12:\n" +
	"\assh_key\x18\a \x01(\v2\x1f.proton_pass_item_v1.ItemSSHKeyH\x00R\x06sshKey\x123\n" +
	"\x04wifi\x18\b \x01(\v2\x1d.proton_pass_item_v1.ItemWifiH\x00R\x04wifi\x129\n" +
	"\x06custom\x18\t \x01(\v2\x1f.proton_pass_item_v1.ItemCustomH\x00R\x06customB\t\n" +
	"\acontent\"\x91\x02\n" +
	"\x04Item\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1d.proton_pass_item_v1.MetadataR\bmetadata\x126\n" +
	"\acontent\x18\x02 \x01(\v2\x1c.proton_pass_item_v1.ContentR\acontent\x12R\n" +
	"\x11platform_specific\x18\x03 \x01(\v2%.proton_pass_item_v1.PlatformSpecificR\x10platformSpecific\x12B\n" +
	"\fextra_fields\x18\x04 \x03(\v2\x1f.proton_pass_item_v1.ExtraFieldR\vextraFields*Q\n" +
	"\fWifiSecurity\x12\x1b\n" +
	"\x17UnspecifiedWifiSecurity\x10\x00\x12\a\n" +
	"\x03WPA\x10\x01\x12\b\n" +
	"\x04WPA2\x10\x02\x12\b\n" +
	"\x04WPA3\x10\x03\x12\a\n" +
	"\x03WEP\x10\x04*U\n" +
	"\bCardType\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\t\n" +
	"\x05Other\x10\x01\x12\b\n" +
	"\x04Visa\x10\x02\x12\x0e\n" +
	"\n" +
	"Mastercard\x10\x03\x12\x13\n" +
	"\x0fAmericanExpress\x10\x04B/Z-github.com/roman-16/proton-cli/internal/protob\x06proto3"

var (
	file_item_v1_proto_rawDescOnce sync.Once
	file_item_v1_proto_rawDescData []byte
)

func file_item_v1_proto_rawDescGZIP() []byte {
	file_item_v1_proto_rawDescOnce.Do(func() {
		file_item_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_v1_proto_rawDesc), len(file_item_v1_proto_rawDesc)))
	})
	return file_item_v1_proto_rawDescData
}

var file_item_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_item_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_item_v1_proto_goTypes = []any{
	(WifiSecurity)(0),             // 0: proton_pass_item_v1.WifiSecurity
	(CardType)(0),                 // 1: proton_pass_item_v1.CardType
	(*ItemNote)(nil),              // 2: proton_pass_item_v1.ItemNote
	(*PasskeyCreationData)(nil),   // 3: proton_pass_item_v1.PasskeyCreationData
	(*Passkey)(nil),               // 4: proton_pass_item_v1.Passkey
	(*ItemLogin)(nil),             // 5: proton_pass_item_v1.ItemLogin
	(*ItemAlias)(nil),             // 6: proton_pass_item_v1.ItemAlias
	(*CustomSection)(nil),         // 7: proton_pass_item_v1.CustomSection
	(*ItemCustom)(nil),            // 8: proton_pass_item_v1.ItemCustom
	(*ItemSSHKey)(nil),            // 9: proton_pass_item_v1.ItemSSHKey
	(*ItemWifi)(nil),              // 10: proton_pass_item_v1.ItemWifi
	(*ItemCreditCard)(nil),        // 11: proton_pass_item_v1.ItemCreditCard
	(*ItemIdentity)(nil),          // 12: proton_pass_item_v1.ItemIdentity
	(*AllowedAndroidApp)(nil),     // 13: proton_pass_item_v1.AllowedAndroidApp
	(*AndroidSpecific)(nil),       // 14: proton_pass_item_v1.AndroidSpecific
	(*PlatformSpecific)(nil),      // 15: proton_pass_item_v1.PlatformSpecific
	(*ExtraTotp)(nil),             // 16: proton_pass_item_v1.ExtraTotp
	(*ExtraTextField)(nil),        // 17: proton_pass_item_v1.ExtraTextField
	(*ExtraHiddenField)(nil),      // 18: proton_pass_item_v1.ExtraHiddenField
	(*ExtraTimestampField)(nil),   // 19: proton_pass_item_v1.ExtraTimestampField
	(*ExtraField)(nil),            // 20: proton_pass_item_v1.ExtraField
	(*Metadata)(nil),              // 21: proton_pass_item_v1.Metadata
	(*Content)(nil),               // 22: proton_pass_item_v1.Content
	(*Item)(nil),                  // 23: proton_pass_item_v1.Item
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_item_v1_proto_depIdxs = []int32{
	3,  // 0: proton_pass_item_v1.Passkey.creation_data:type_name -> proton_pass_item_v1.PasskeyCreationData
	4,  // 1: proton_pass_item_v1.ItemLogin.passkeys:type_name -> proton_pass_item_v1.Passkey
	20, // 2: proton_pass_item_v1.CustomSection.section_fields:type_name -> proton_pass_item_v1.ExtraField
	7,  // 3: proton_pass_item_v1.ItemCustom.sections:type_name -> proton_pass_item_v1.CustomSection
	7,  // 4: proton_pass_item_v1.ItemSSHKey.sections:type_name -> proton_pass_item_v1.CustomSection
	0,  // 5: proton_pass_item_v1.ItemWifi.security:type_name -> proton_pass_item_v1.WifiSecurity
	7,  // 6: proton_pass_item_v1.ItemWifi.sections:type_name -> proton_pass_item_v1.CustomSection
	1,  // 7: proton_pass_item_v1.ItemCreditCard.card_type:type_name -> proton_pass_item_v1.CardType
	20, // 8: proton_pass_item_v1.ItemIdentity.extra_personal_details:type_name -> proton_pass_item_v1.ExtraField
	20, // 9: proton_pass_item_v1.ItemIdentity.extra_address_details:type_name -> proton_pass_item_v1.ExtraField
	20, // 10: proton_pass_item_v1.ItemIdentity.extra_contact_details:type_name -> proton_pass_item_v1.ExtraField
	20, // 11: proton_pass_item_v1.ItemIdentity.extra_work_details:type_name -> proton_pass_item_v1.ExtraField
	7,  // 12: proton_pass_item_v1.ItemIdentity.extra_sections:type_name -> proton_pass_item_v1.CustomSection
	13, // 13: proton_pass_item_v1.AndroidSpecific.allowed_apps:type_name -> proton_pass_item_v1.AllowedAndroidApp
	14, // 14: proton_pass_item_v1.PlatformSpecific.android:type_name -> proton_pass_item_v1.AndroidSpecific
	24, // 15: proton_pass_item_v1.ExtraTimestampField.timestamp:type_name -> google.protobuf.Timestamp
	16, // 16: proton_pass_item_v1.ExtraField.totp:type_name -> proton_pass_item_v1.ExtraTotp
	17, // 17: proton_pass_item_v1.ExtraField.text:type_name -> proton_pass_item_v1.ExtraTextField
	18, // 18: proton_pass_item_v1.ExtraField.hidden:type_name -> proton_pass_item_v1.ExtraHiddenField
	19, // 19: proton_pass_item_v1.ExtraField.timestamp:type_name -> proton_pass_item_v1.ExtraTimestampField
	2,  // 20: proton_pass_item_v1.Content.note:type_name -> proton_pass_item_v1.ItemNote
	5,  // 21: proton_pass_item_v1.Content.login:type_name -> proton_pass_item_v1.ItemLogin
	6,  // 22: proton_pass_item_v1.Content.alias:type_name -> proton_pass_item_v1.ItemAlias
	11, // 23: proton_pass_item_v1.Content.credit_card:type_name -> proton_pass_item_v1.ItemCreditCard
	12, // 24: proton_pass_item_v1.Content.identity:type_name -> proton_pass_item_v1.ItemIdentity
	9,  // 25: proton_pass_item_v1.Content.ssh_key:type_name -> proton_pass_item_v1.ItemSSHKey
	10, // 26: proton_pass_item_v1.Content.wifi:type_name -> proton_pass_item_v1.ItemWifi
	8,  // 27: proton_pass_item_v1.Content.custom:type_name -> proton_pass_item_v1.ItemCustom
	21, // 28: proton_pass_item_v1.Item.metadata:type_name -> proton_pass_item_v1.Metadata
	22, // 29: proton_pass_item_v1.Item.content:type_name -> proton_pass_item_v1.Content
	15, // 30: proton_pass_item_v1.Item.platform_specific:type_name -> proton_pass_item_v1.PlatformSpecific
	20, // 31: proton_pass_item_v1.Item.extra_fields:type_name -> proton_pass_item_v1.ExtraField
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_item_v1_proto_init() }
func file_item_v1_proto_init() {
	if File_item_v1_proto != nil {
		return
	}
	file_item_v1_proto_msgTypes[18].OneofWrappers = []any{
		(*ExtraField_Totp)(nil),
		(*ExtraField_Text)(nil),
		(*ExtraField_Hidden)(nil),
		(*ExtraField_Timestamp)(nil),
	}
	file_item_v1_proto_msgTypes[20].OneofWrappers = []any{
		(*Content_Note)(nil),
		(*Content_Login)(nil),
		(*Content_Alias)(nil),
		(*Content_CreditCard)(nil),
		(*Content_Identity)(nil),
		(*Content_SshKey)(nil),
		(*Content_Wifi)(nil),
		(*Content_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_v1_proto_rawDesc), len(file_item_v1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_v1_proto_goTypes,
		DependencyIndexes: file_item_v1_proto_depIdxs,
		EnumInfos:         file_item_v1_proto_enumTypes,
		MessageInfos:      file_item_v1_proto_msgTypes,
	}.Build()
	File_item_v1_proto = out.File
	file_item_v1_proto_goTypes = nil
	file_item_v1_proto_depIdxs = nil
}
