// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: vault-v1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VaultIcon int32

const (
	VaultIcon_ICON_UNSPECIFIED VaultIcon = 0
	VaultIcon_ICON_CUSTOM      VaultIcon = 1
	VaultIcon_ICON1            VaultIcon = 2
	VaultIcon_ICON2            VaultIcon = 3
	VaultIcon_ICON3            VaultIcon = 4
	VaultIcon_ICON4            VaultIcon = 5
	VaultIcon_ICON5            VaultIcon = 6
	VaultIcon_ICON6            VaultIcon = 7
	VaultIcon_ICON7            VaultIcon = 8
	VaultIcon_ICON8            VaultIcon = 9
	VaultIcon_ICON9            VaultIcon = 10
	VaultIcon_ICON10           VaultIcon = 11
	VaultIcon_ICON11           VaultIcon = 12
	VaultIcon_ICON12           VaultIcon = 13
	VaultIcon_ICON13           VaultIcon = 14
	VaultIcon_ICON14           VaultIcon = 15
	VaultIcon_ICON15           VaultIcon = 16
	VaultIcon_ICON16           VaultIcon = 17
	VaultIcon_ICON17           VaultIcon = 18
	VaultIcon_ICON18           VaultIcon = 19
	VaultIcon_ICON19           VaultIcon = 20
	VaultIcon_ICON20           VaultIcon = 21
	VaultIcon_ICON21           VaultIcon = 22
	VaultIcon_ICON22           VaultIcon = 23
	VaultIcon_ICON23           VaultIcon = 24
	VaultIcon_ICON24           VaultIcon = 25
	VaultIcon_ICON25           VaultIcon = 26
	VaultIcon_ICON26           VaultIcon = 27
	VaultIcon_ICON27           VaultIcon = 28
	VaultIcon_ICON28           VaultIcon = 29
	VaultIcon_ICON29           VaultIcon = 30
	VaultIcon_ICON30           VaultIcon = 31
)

// Enum value maps for VaultIcon.
var (
	VaultIcon_name = map[int32]string{
		0:  "ICON_UNSPECIFIED",
		1:  "ICON_CUSTOM",
		2:  "ICON1",
		3:  "ICON2",
		4:  "ICON3",
		5:  "ICON4",
		6:  "ICON5",
		7:  "ICON6",
		8:  "ICON7",
		9:  "ICON8",
		10: "ICON9",
		11: "ICON10",
		12: "ICON11",
		13: "ICON12",
		14: "ICON13",
		15: "ICON14",
		16: "ICON15",
		17: "ICON16",
		18: "ICON17",
		19: "ICON18",
		20: "ICON19",
		21: "ICON20",
		22: "ICON21",
		23: "ICON22",
		24: "ICON23",
		25: "ICON24",
		26: "ICON25",
		27: "ICON26",
		28: "ICON27",
		29: "ICON28",
		30: "ICON29",
		31: "ICON30",
	}
	VaultIcon_value = map[string]int32{
		"ICON_UNSPECIFIED": 0,
		"ICON_CUSTOM":      1,
		"ICON1":            2,
		"ICON2":            3,
		"ICON3":            4,
		"ICON4":            5,
		"ICON5":            6,
		"ICON6":            7,
		"ICON7":            8,
		"ICON8":            9,
		"ICON9":            10,
		"ICON10":           11,
		"ICON11":           12,
		"ICON12":           13,
		"ICON13":           14,
		"ICON14":           15,
		"ICON15":           16,
		"ICON16":           17,
		"ICON17":           18,
		"ICON18":           19,
		"ICON19":           20,
		"ICON20":           21,
		"ICON21":           22,
		"ICON22":           23,
		"ICON23":           24,
		"ICON24":           25,
		"ICON25":           26,
		"ICON26":           27,
		"ICON27":           28,
		"ICON28":           29,
		"ICON29":           30,
		"ICON30":           31,
	}
)

func (x VaultIcon) Enum() *VaultIcon {
	p := new(VaultIcon)
	*p = x
	return p
}

func (x VaultIcon) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VaultIcon) Descriptor() protoreflect.EnumDescriptor {
	return file_vault_v1_proto_enumTypes[0].Descriptor()
}

func (VaultIcon) Type() protoreflect.EnumType {
	return &file_vault_v1_proto_enumTypes[0]
}

func (x VaultIcon) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VaultIcon.Descriptor instead.
func (VaultIcon) EnumDescriptor() ([]byte, []int) {
	return file_vault_v1_proto_rawDescGZIP(), []int{0}
}

type VaultColor int32

const (
	VaultColor_COLOR_UNSPECIFIED VaultColor = 0
	VaultColor_COLOR_CUSTOM      VaultColor = 1
	VaultColor_COLOR1            VaultColor = 2
	VaultColor_COLOR2            VaultColor = 3
	VaultColor_COLOR3            VaultColor = 4
	VaultColor_COLOR4            VaultColor = 5
	VaultColor_COLOR5            VaultColor = 6
	VaultColor_COLOR6            VaultColor = 7
	VaultColor_COLOR7            VaultColor = 8
	VaultColor_COLOR8            VaultColor = 9
	VaultColor_COLOR9            VaultColor = 10
	VaultColor_COLOR10           VaultColor = 11
)

// Enum value maps for VaultColor.
var (
	VaultColor_name = map[int32]string{
		0:  "COLOR_UNSPECIFIED",
		1:  "COLOR_CUSTOM",
		2:  "COLOR1",
		3:  "COLOR2",
		4:  "COLOR3",
		5:  "COLOR4",
		6:  "COLOR5",
		7:  "COLOR6",
		8:  "COLOR7",
		9:  "COLOR8",
		10: "COLOR9",
		11: "COLOR10",
	}
	VaultColor_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_CUSTOM":      1,
		"COLOR1":            2,
		"COLOR2":            3,
		"COLOR3":            4,
		"COLOR4":            5,
		"COLOR5":            6,
		"COLOR6":            7,
		"COLOR7":            8,
		"COLOR8":            9,
		"COLOR9":            10,
		"COLOR10":           11,
	}
)

func (x VaultColor) Enum() *VaultColor {
	p := new(VaultColor)
	*p = x
	return p
}

func (x VaultColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VaultColor) Descriptor() protoreflect.EnumDescriptor {
	return file_vault_v1_proto_enumTypes[1].Descriptor()
}

func (VaultColor) Type() protoreflect.EnumType {
	return &file_vault_v1_proto_enumTypes[1]
}

func (x VaultColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VaultColor.Descriptor instead.
func (VaultColor) EnumDescriptor() ([]byte, []int) {
	return file_vault_v1_proto_rawDescGZIP(), []int{1}
}

type VaultDisplayPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Icon          VaultIcon              `protobuf:"varint,1,opt,name=icon,proto3,enum=proton_pass_vault_v1.VaultIcon" json:"icon,omitempty"`
	Color         VaultColor             `protobuf:"varint,2,opt,name=color,proto3,enum=proton_pass_vault_v1.VaultColor" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultDisplayPreferences) Reset() {
	*x = VaultDisplayPreferences{}
	mi := &file_vault_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultDisplayPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultDisplayPreferences) ProtoMessage() {}

func (x *VaultDisplayPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultDisplayPreferences.ProtoReflect.Descriptor instead.
func (*VaultDisplayPreferences) Descriptor() ([]byte, []int) {
	return file_vault_v1_proto_rawDescGZIP(), []int{0}
}

func (x *VaultDisplayPreferences) GetIcon() VaultIcon {
	if x != nil {
		return x.Icon
	}
	return VaultIcon_ICON_UNSPECIFIED
}

func (x *VaultDisplayPreferences) GetColor() VaultColor {
	if x != nil {
		return x.Color
	}
	return VaultColor_COLOR_UNSPECIFIED
}

type Vault struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Display       *VaultDisplayPreferences `protobuf:"bytes,3,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vault) Reset() {
	*x = Vault{}
	mi := &file_vault_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vault) ProtoMessage() {}

func (x *Vault) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vault.ProtoReflect.Descriptor instead.
func (*Vault) Descriptor() ([]byte, []int) {
	return file_vault_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Vault) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vault) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vault) GetDisplay() *VaultDisplayPreferences {
	if x != nil {
		return x.Display
	}
	return nil
}

var File_vault_v1_proto protoreflect.FileDescriptor

const file_vault_v1_proto_rawDesc = "" +
	"\n" +
	"\x0evault-v1.proto\x12\x14proton_pass_vault_v1\"\x86\x01\n" +
	"\x17VaultDisplayPreferences\x123\n" +
	"\x04icon\x18\x01 \x01(\x0e2\x1f.proton_pass_vault_v1.VaultIconR\x04icon\x126\n" +
	"\x05color\x18\x02 \x01(\x0e2 .proton_pass_vault_v1.VaultColorR\x05color\"\x86\x01\n" +
	"\x05Vault\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12G\n" +
	"\adisplay\x18\x03 \x01(\v2-.proton_pass_vault_v1.VaultDisplayPreferencesR\adisplay*\x91\x03\n" +
	"\tVaultIcon\x12\x14\n" +
	"\x10ICON_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vICON_CUSTOM\x10\x01\x12\t\n" +
	"\x05ICON1\x10\x02\x12\t\n" +
	"\x05ICON2\x10\x03\x12\t\n" +
	"\x05ICON3\x10\x04\x12\t\n" +
	"\x05ICON4\x10\x05\x12\t\n" +
	"\x05ICON5\x10\x06\x12\t\n" +
	"\x05ICON6\x10\a\x12\t\n" +
	"\x05ICON7\x10\b\x12\t\n" +
	"\x05ICON8\x10\t\x12\t\n" +
	"\x05ICON9\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06ICON10\x10\v\x12\n" +
	"\n" +
	"\x06ICON11\x10\f\x12\n" +
	"\n" +
	"\x06ICON12\x10\r\x12\n" +
	"\n" +
	"\x06ICON13\x10\x0e\x12\n" +
	"\n" +
	"\x06ICON14\x10\x0f\x12\n" +
	"\n" +
	"\x06ICON15\x10\x10\x12\n" +
	"\n" +
	"\x06ICON16\x10\x11\x12\n" +
	"\n" +
	"\x06ICON17\x10\x12\x12\n" +
	"\n" +
	"\x06ICON18\x10\x13\x12\n" +
	"\n" +
	"\x06ICON19\x10\x14\x12\n" +
	"\n" +
	"\x06ICON20\x10\x15\x12\n" +
	"\n" +
	"\x06ICON21\x10\x16\x12\n" +
	"\n" +
	"\x06ICON22\x10\x17\x12\n" +
	"\n" +
	"\x06ICON23\x10\x18\x12\n" +
	"\n" +
	"\x06ICON24\x10\x19\x12\n" +
	"\n" +
	"\x06ICON25\x10\x1a\x12\n" +
	"\n" +
	"\x06ICON26\x10\x1b\x12\n" +
	"\n" +
	"\x06ICON27\x10\x1c\x12\n" +
	"\n" +
	"\x06ICON28\x10\x1d\x12\n" +
	"\n" +
	"\x06ICON29\x10\x1e\x12\n" +
	"\n" +
	"\x06ICON30\x10\x1f*\xae\x01\n" +
	"\n" +
	"VaultColor\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCOLOR_CUSTOM\x10\x01\x12\n" +
	"\n" +
	"\x06COLOR1\x10\x02\x12\n" +
	"\n" +
	"\x06COLOR2\x10\x03\x12\n" +
	"\n" +
	"\x06COLOR3\x10\x04\x12\n" +
	"\n" +
	"\x06COLOR4\x10\x05\x12\n" +
	"\n" +
	"\x06COLOR5\x10\x06\x12\n" +
	"\n" +
	"\x06COLOR6\x10\a\x12\n" +
	"\n" +
	"\x06COLOR7\x10\b\x12\n" +
	"\n" +
	"\x06COLOR8\x10\t\x12\n" +
	"\n" +
	"\x06COLOR9\x10\n" +
	"\x12\v\n" +
	"\aCOLOR10\x10\vB/Z-github.com/roman-16/proton-cli/internal/protob\x06proto3"

var (
	file_vault_v1_proto_rawDescOnce sync.Once
	file_vault_v1_proto_rawDescData []byte
)

func file_vault_v1_proto_rawDescGZIP() []byte {
	file_vault_v1_proto_rawDescOnce.Do(func() {
		file_vault_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_v1_proto_rawDesc), len(file_vault_v1_proto_rawDesc)))
	})
	return file_vault_v1_proto_rawDescData
}

var file_vault_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vault_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vault_v1_proto_goTypes = []any{
	(VaultIcon)(0),                  // 0: proton_pass_vault_v1.VaultIcon
	(VaultColor)(0),                 // 1: proton_pass_vault_v1.VaultColor
	(*VaultDisplayPreferences)(nil), // 2: proton_pass_vault_v1.VaultDisplayPreferences
	(*Vault)(nil),                   // 3: proton_pass_vault_v1.Vault
}
var file_vault_v1_proto_depIdxs = []int32{
	0, // 0: proton_pass_vault_v1.VaultDisplayPreferences.icon:type_name -> proton_pass_vault_v1.VaultIcon
	1, // 1: proton_pass_vault_v1.VaultDisplayPreferences.color:type_name -> proton_pass_vault_v1.VaultColor
	2, // 2: proton_pass_vault_v1.Vault.display:type_name -> proton_pass_vault_v1.VaultDisplayPreferences
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vault_v1_proto_init() }
func file_vault_v1_proto_init() {
	if File_vault_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_v1_proto_rawDesc), len(file_vault_v1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vault_v1_proto_goTypes,
		DependencyIndexes: file_vault_v1_proto_depIdxs,
		EnumInfos:         file_vault_v1_proto_enumTypes,
		MessageInfos:      file_vault_v1_proto_msgTypes,
	}.Build()
	File_vault_v1_proto = out.File
	file_vault_v1_proto_goTypes = nil
	file_vault_v1_proto_depIdxs = nil
}
