// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: action-payload-v1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	VaultName     string                 `protobuf:"bytes,2,opt,name=vault_name,json=vaultName,proto3" json:"vault_name,omitempty"`
	ItemName      string                 `protobuf:"bytes,3,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	FolderName    string                 `protobuf:"bytes,4,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAction) Reset() {
	*x = AgentAction{}
	mi := &file_action_payload_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAction) ProtoMessage() {}

func (x *AgentAction) ProtoReflect() protoreflect.Message {
	mi := &file_action_payload_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAction.ProtoReflect.Descriptor instead.
func (*AgentAction) Descriptor() ([]byte, []int) {
	return file_action_payload_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AgentAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AgentAction) GetVaultName() string {
	if x != nil {
		return x.VaultName
	}
	return ""
}

func (x *AgentAction) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *AgentAction) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

type ActionPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ActionPayload_AgentAction
	Content       isActionPayload_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionPayload) Reset() {
	*x = ActionPayload{}
	mi := &file_action_payload_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionPayload) ProtoMessage() {}

func (x *ActionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_action_payload_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionPayload.ProtoReflect.Descriptor instead.
func (*ActionPayload) Descriptor() ([]byte, []int) {
	return file_action_payload_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ActionPayload) GetContent() isActionPayload_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ActionPayload) GetAgentAction() *AgentAction {
	if x != nil {
		if x, ok := x.Content.(*ActionPayload_AgentAction); ok {
			return x.AgentAction
		}
	}
	return nil
}

type isActionPayload_Content interface {
	isActionPayload_Content()
}

type ActionPayload_AgentAction struct {
	AgentAction *AgentAction `protobuf:"bytes,1,opt,name=agent_action,json=agentAction,proto3,oneof"`
}

func (*ActionPayload_AgentAction) isActionPayload_Content() {}

var File_action_payload_v1_proto protoreflect.FileDescriptor

const file_action_payload_v1_proto_rawDesc = "" +
	"\n" +
	"\x17action-payload-v1.proto\x12\x1dproton_pass_action_payload_v1\"\x82\x01\n" +
	"\vAgentAction\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"vault_name\x18\x02 \x01(\tR\tvaultName\x12\x1b\n" +
	"\titem_name\x18\x03 \x01(\tR\bitemName\x12\x1f\n" +
	"\vfolder_name\x18\x04 \x01(\tR\n" +
	"folderName\"k\n" +
	"\rActionPayload\x12O\n" +
	"\fagent_action\x18\x01 \x01(\v2*.proton_pass_action_payload_v1.AgentActionH\x00R\vagentActionB\t\n" +
	"\acontentB/Z-github.com/roman-16/proton-cli/internal/protob\x06proto3"

var (
	file_action_payload_v1_proto_rawDescOnce sync.Once
	file_action_payload_v1_proto_rawDescData []byte
)

func file_action_payload_v1_proto_rawDescGZIP() []byte {
	file_action_payload_v1_proto_rawDescOnce.Do(func() {
		file_action_payload_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_payload_v1_proto_rawDesc), len(file_action_payload_v1_proto_rawDesc)))
	})
	return file_action_payload_v1_proto_rawDescData
}

var file_action_payload_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_action_payload_v1_proto_goTypes = []any{
	(*AgentAction)(nil),   // 0: proton_pass_action_payload_v1.AgentAction
	(*ActionPayload)(nil), // 1: proton_pass_action_payload_v1.ActionPayload
}
var file_action_payload_v1_proto_depIdxs = []int32{
	0, // 0: proton_pass_action_payload_v1.ActionPayload.agent_action:type_name -> proton_pass_action_payload_v1.AgentAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_action_payload_v1_proto_init() }
func file_action_payload_v1_proto_init() {
	if File_action_payload_v1_proto != nil {
		return
	}
	file_action_payload_v1_proto_msgTypes[1].OneofWrappers = []any{
		(*ActionPayload_AgentAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_payload_v1_proto_rawDesc), len(file_action_payload_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_payload_v1_proto_goTypes,
		DependencyIndexes: file_action_payload_v1_proto_depIdxs,
		MessageInfos:      file_action_payload_v1_proto_msgTypes,
	}.Build()
	File_action_payload_v1_proto = out.File
	file_action_payload_v1_proto_goTypes = nil
	file_action_payload_v1_proto_depIdxs = nil
}
