// @ts-check
import starlight from "@astrojs/starlight";
import { defineConfig, fontProviders } from "astro/config";
import starlightLinksValidator from "starlight-links-validator";
import starlightLlmsTxt from "starlight-llms-txt";
import starlightThemeBlack from "starlight-theme-black";

import { description, origin, repo, social } from "./site.ts";

export default defineConfig({
  fonts: [
    {
      cssVariable: "--font-inter",
      name: "Inter",
      provider: fontProviders.fontsource(),
    },
  ],
  integrations: [
    starlight({
      customCss: ["./src/styles/proton.css"],
      description,
      /*
       * Half of what is shown here is terminal output, and a table that wraps
       * is a table destroyed: the columns a reader is matching up land under
       * each other. So a long line scrolls, and every block keeps the shape it
       * has in a terminal.
       *
       * A crontab has no grammar to highlight it with, and a schedule is five
       * fields and a command either way.
       */
      expressiveCode: {
        shiki: { langAlias: { cron: "txt" } },
      },
      favicon: "/favicon.svg",
      /*
       * Starlight declares a large summary card and leaves the image to the
       * site, so without these every share of every page renders an empty
       * rectangle.
       */
      head: [
        { attrs: { content: social, property: "og:image" }, tag: "meta" },
        { attrs: { content: "1200", property: "og:image:width" }, tag: "meta" },
        { attrs: { content: "630", property: "og:image:height" }, tag: "meta" },
        {
          attrs: {
            content: "proton-cli, your CLI for Proton Mail, Drive, Calendar, Pass and Contacts",
            property: "og:image:alt",
          },
          tag: "meta",
        },
        { attrs: { content: social, name: "twitter:image" }, tag: "meta" },
      ],
      lastUpdated: true,
      logo: { alt: "", src: "./src/assets/logo.svg" },
      plugins: [
        starlightThemeBlack({
          /*
           * A page here is a command line and a paragraph about it. Handing
           * either to somebody else's chat window is not what a reader came for,
           * and the control costs a button on every page to offer it.
           */
          docs: { showMarkdownActions: false },
          navLinks: [
            { label: "Docs", link: "/installation/" },
            { label: "Commands", link: "/commands/" },
            { label: "FAQ", link: "/faq/" },
            { label: "Stats", link: "/stats/" },
          ],
        }),
        starlightLlmsTxt({
          description: `${description} One grammar: proton <app> <collection> <verb>.`,
          projectName: "proton-cli",
          /*
           * Somebody asking a model how to do something with this wants the
           * grammar before the catalogue: the shape is what makes the other two
           * hundred commands guessable, and the reference is what it then reads.
           */
          promote: ["index", "quickstart", "language", "output", "faq"],
        }),
        starlightLinksValidator(),
      ],
      /*
       * The order is the order somebody meets the tool in: install it, learn the
       * sentence, then one page per app for the doing, then the exhaustive list
       * for the looking-up, then the questions that come after.
       *
       * Labels are given here because a page's title is written to be read in a
       * search result - "Proton Mail from the command line" - and a sidebar wants
       * the word, not the sentence. The command pages are listed rather than
       * autogenerated because autogeneration sorts them alphabetically, which
       * puts the raw API above Mail and Drive.
       */
      sidebar: [
        {
          items: [
            { label: "Install", slug: "installation" },
            { label: "Quickstart", slug: "quickstart" },
            { label: "How commands read", slug: "language" },
          ],
          label: "Start here",
        },
        {
          items: [
            { label: "Mail", slug: "apps/mail" },
            { label: "Drive", slug: "apps/drive" },
            { label: "Calendar", slug: "apps/calendar" },
            { label: "Pass", slug: "apps/pass" },
            { label: "Contacts", slug: "apps/contacts" },
            { label: "Account", slug: "apps/account" },
            { label: "Raw API", slug: "apps/api" },
          ],
          label: "The apps",
        },
        {
          items: [
            { label: "Scripting", slug: "scripting" },
            { label: "Configuration", slug: "configuration" },
          ],
          label: "Automating it",
        },
        {
          items: [
            { label: "Commands", slug: "commands" },
            "commands/mail",
            "commands/drive",
            "commands/calendar",
            "commands/pass",
            "commands/contacts",
            "commands/account",
            "commands/api",
            "commands/self",
            { label: "Output", slug: "output" },
            { label: "Limits", slug: "limitations" },
            { label: "Changelog", slug: "changelog" },
            { label: "Proton API reference", link: "/api-reference/" },
          ],
          label: "Reference",
        },
        {
          items: [
            { label: "FAQ", slug: "faq" },
            { label: "Troubleshooting", slug: "troubleshooting" },
            { label: "Security", slug: "how-it-works" },
            { label: "Design notes", slug: "design-notes" },
          ],
          label: "Answers",
        },
      ],
      social: [{ href: repo, icon: "github", label: "GitHub" }],
      title: "proton-cli",
    }),
  ],
  /*
   * Pages that were linked from elsewhere before their content found a better
   * home. Astro writes each as a redirecting stub, so an old bookmark lands on
   * the page that answers it rather than on a 404.
   */
  redirects: {
    "/getting-started/": "/quickstart/",
    "/human-verification/": "/troubleshooting/",
    "/references/": "/language/",
  },
  site: origin,
  trailingSlash: "always",
});
