// @ts-check
import starlight from "@astrojs/starlight";
import { defineConfig, fontProviders } from "astro/config";
import starlightLinksValidator from "starlight-links-validator";
import starlightLlmsTxt from "starlight-llms-txt";
import starlightThemeBlack from "starlight-theme-black";

import { description, origin, repo, social } from "./site.ts";

/*
 * The sidebar keeps its scroll position across a navigation.
 *
 * It is registered from a plugin rather than from `components`, because the
 * theme warns about any override it finds in the configuration - and this one is
 * the very thing that warning recommends, since it renders the theme's own
 * sidebar. Declared after the theme, it updates the same setting without being
 * seen.
 */
const sidebarScroll = {
  hooks: {
    "config:setup"({ config, updateConfig }) {
      updateConfig({
        components: { ...config.components, Sidebar: "./src/components/Sidebar.astro" },
      });
    },
  },
  name: "proton-cli-sidebar-scroll",
};

export default defineConfig({
  fonts: [
    {
      cssVariable: "--font-inter",
      name: "Inter",
      provider: fontProviders.fontsource(),
    },
  ],
  integrations: [
    starlight({
      customCss: ["./src/styles/proton.css"],
      description,
      /*
       * Half of what is shown here is terminal output, and a table that wraps
       * is a table destroyed: the columns a reader is matching up land under
       * each other. So a long line scrolls, and every block keeps the shape it
       * has in a terminal.
       *
       * A crontab has no grammar to highlight it with, and a schedule is five
       * fields and a command either way.
       */
      expressiveCode: {
        shiki: { langAlias: { cron: "txt" } },
      },
      favicon: "/favicon.svg",
      /*
       * Starlight declares a large summary card and leaves the image to the
       * site, so without these every share of every page renders an empty
       * rectangle.
       */
      head: [
        { attrs: { content: social, property: "og:image" }, tag: "meta" },
        { attrs: { content: "1200", property: "og:image:width" }, tag: "meta" },
        { attrs: { content: "630", property: "og:image:height" }, tag: "meta" },
        {
          attrs: {
            content: "proton-cli, your CLI for Proton Mail, Drive, Calendar, Pass and Contacts",
            property: "og:image:alt",
          },
          tag: "meta",
        },
        { attrs: { content: social, name: "twitter:image" }, tag: "meta" },
      ],
      lastUpdated: true,
      logo: { alt: "", src: "./src/assets/logo.svg" },
      plugins: [
        starlightThemeBlack({
          /*
           * A page here is a command line and a paragraph about it. Handing
           * either to somebody else's chat window is not what a reader came for,
           * and the control costs a button on every page to offer it.
           */
          docs: { showMarkdownActions: false },
          navLinks: [
            { label: "Docs", link: "/install/" },
            { label: "Commands", link: "/about/commands/" },
            { label: "FAQ", link: "/about/faq/" },
            { label: "Stats", link: "/stats/" },
          ],
        }),
        starlightLlmsTxt({
          description,
          projectName: "proton-cli",
          /*
           * Somebody asking a model how to do something with this wants the
           * grammar before the catalogue: the shape is what makes the other two
           * hundred commands guessable, and the reference is what it then reads.
           */
          promote: ["index", "first-commands", "commands", "using/output", "about/faq"],
        }),
        starlightLinksValidator(),
        sidebarScroll,
      ],
      /*
       * One section per app, holding its guide and the reference pages for its
       * collections, so everything about Mail is in one place rather than under
       * two identically labelled entries in two sections. A reference page is
       * named for the command line it documents, which is also its URL: `proton
       * mail messages send` is at /mail/messages/#send.
       *
       * Labels are given here because a page's title is written to be read in a
       * search result and a sidebar wants the word rather than the sentence. The
       * collections are listed rather than autogenerated because autogeneration
       * sorts them alphabetically, which buries the one most people want.
       */
      sidebar: [
        {
          items: [
            { label: "Install", slug: "install" },
            { label: "First commands", slug: "first-commands" },
            { label: "How a command is built", slug: "commands" },
            { label: "Managing proton itself", slug: "proton" },
          ],
          label: "Start here",
        },
        {
          items: [
            { label: "Guide", slug: "mail" },
            "mail/messages",
            "mail/conversations",
            "mail/drafts",
            "mail/settings",
          ],
          label: "Mail",
        },
        {
          items: [
            { label: "Guide", slug: "drive" },
            "drive/items",
            "drive/trash",
            "drive/photos",
            "drive/sharing",
            "drive/shared",
            "drive/invitations",
            "drive/settings",
          ],
          label: "Drive",
        },
        {
          items: [
            { label: "Guide", slug: "calendar" },
            "calendar/events",
            "calendar/reminders",
            "calendar/invitations",
            "calendar/settings",
          ],
          label: "Calendar",
        },
        {
          items: [
            { label: "Guide", slug: "pass" },
            "pass/items",
            "pass/vaults",
            "pass/aliases",
            "pass/links",
            "pass/sharing",
            "pass/shared",
            "pass/invitations",
            "pass/trash",
            "pass/breaches",
            "pass/settings",
            { label: "import, export, generate", slug: "pass/pass" },
          ],
          label: "Pass",
        },
        {
          items: [
            { label: "Guide", slug: "contacts" },
            "contacts/contacts",
            "contacts/groups",
            "contacts/keys",
          ],
          label: "Contacts",
        },
        {
          items: [
            { label: "Guide", slug: "account" },
            "account/account",
            "account/sessions",
            "account/profiles",
            "account/settings",
          ],
          label: "Account",
        },
        {
          items: [{ label: "Guide", slug: "api" }, "api/api"],
          label: "Raw API",
        },
        {
          items: [
            { label: "Naming what to act on", slug: "using/naming" },
            { label: "Filters and bulk changes", slug: "using/filters" },
            { label: "Dry runs and confirmations", slug: "using/confirmations" },
            { label: "Output and exit codes", slug: "using/output" },
            { label: "Scripting", slug: "using/scripting" },
            { label: "Settings, files and environment", slug: "using/settings" },
          ],
          label: "Everyday use",
        },
        {
          items: [
            { label: "Troubleshooting", slug: "help/troubleshooting" },
            { label: "What it can't do", slug: "help/limits" },
          ],
          label: "When something goes wrong",
        },
        {
          items: [
            { label: "FAQ", slug: "about/faq" },
            { label: "Security and encryption", slug: "about/security" },
            { label: "Why it works this way", slug: "about/why" },
            { label: "All commands", slug: "about/commands" },
            { label: "Changelog", slug: "changelog" },
            { label: "Proton API reference", link: "/api-reference/" },
          ],
          label: "About",
        },
      ],
      social: [{ href: repo, icon: "github", label: "GitHub" }],
      title: "proton-cli",
    }),
  ],
  /*
   * Pages that were linked from elsewhere before their content found a better
   * home. Astro writes each as a redirecting stub, so an old bookmark lands on
   * the page that answers it rather than on a 404.
   */
  redirects: {
    "/apps/account/": "/account/",
    "/apps/api/": "/api/",
    "/apps/calendar/": "/calendar/",
    "/apps/contacts/": "/contacts/",
    "/apps/drive/": "/drive/",
    "/apps/mail/": "/mail/",
    "/apps/pass/": "/pass/",
    "/commands/account/": "/account/",
    "/commands/api/": "/api/",
    "/commands/calendar/": "/calendar/",
    "/commands/contacts/": "/contacts/",
    "/commands/drive/": "/drive/",
    "/commands/mail/": "/mail/",
    "/commands/pass/": "/pass/",
    "/commands/self/": "/proton/",
    "/configuration/": "/using/settings/",
    "/design-notes/": "/about/why/",
    "/faq/": "/about/faq/",
    "/getting-started/": "/first-commands/",
    "/how-it-works/": "/about/security/",
    "/human-verification/": "/help/troubleshooting/",
    "/installation/": "/install/",
    "/language/": "/commands/",
    "/limitations/": "/help/limits/",
    "/output/": "/using/output/",
    "/quickstart/": "/first-commands/",
    "/references/": "/commands/",
    "/scripting/": "/using/scripting/",
    "/troubleshooting/": "/help/troubleshooting/",
  },
  site: origin,
  trailingSlash: "always",
});
